spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    bane: user-service
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://resumerry.cfwdtllyytwh.ap-northeast-2.rds.amazonaws.com:3306/resumerry
    username: admin
    password: dkwneo12!
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  datasource:
#    url: jdbc:mysql://localhost:3306/resumerry?serverTimezone=Asia/Seoul
#    username: root
#    password: 12341234
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: dmswn0261@ajou.ac.kr
    password: okqwxajmtkuzagvu
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
logging:
  level:
    org.hibernate.SQL: debug
jwt:
  secret: sdfasdfa

cloud:
  aws:
    credentials:
      accessKey:   # slack 확인요망
      secretKey:  # slack 확인요망
    s3:
      bucket: resume-file-storage
    region:
      static: ap-northeast-2
    stack:
      auto: false




#
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: 9520awdr0259!
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
#    username: root
#    initialization-mode: always
#    platform: mysql
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#  #  flyway:
#  #    locations: classpath:/db/migration # migration 파일들이 위치하는 directory
#  #    sql-migration-suffixes: ddl        # 파일 확장자
#  #    baseline-on-migrate: true          # flyway_schema_history 테이블을 자동으로 생성할지 여부
#  #    baseline-version: 0                # 최초 버전 정보
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: dmswn0261@ajou.ac.kr
#    password: okqwxajmtkuzagvu
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true
#            required: true
#          auth: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#logging:
#  level:
#    org.hibernate.SQL: debug
#
#server:
#  port: 8081
